name: e2e
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci || npm install
      - run: npx playwright install
      - name: Create .env (optional)
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report